name: test dice



on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: set up java 17
      uses: actions/setup -java@v4
      with:
        distribution: temurin
        java-version: '17'
    - name: check java version
      run: java -version
    - name: build java project
      run: mvn clean package      
